# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 486b40d6210d325bba4c37ee2350a6521c04b35e59c361c45cf36bffeed5bff2b2c5598ddc8ea1ad82e1dbc465e3814b15dda96907b056ef01a4868f61cb4fbb

  key_pass:
    devise_jwt_key_base: 298b8f9f51681a80586573764461fbcdc3cb0639e6af13209a5ad6818926e69aedfad387e92225b7c1f01be1fa72cc3a9c4550669b9e116c0a26c8dc9ae9114a
    chat_room_key_base: 8bcc93effe3f3822aaabd1cf0a7d9c2c
    chat_session_key_base: 4ad11069566fdaad23e629da790eb221 #These are for encrypting the unique identifiers/ keys on the chat room and the chat session

test:
  secret_key_base: 33bb8edf0de44413190923e5de2faffad5b64636822792d8c51377f9b646d6927ef7c6635c14f161d2e8d74532d1094e13deb8d5863dcbea1683920288532b7d
  key_pass:
    devise_jwt_key_base: 40ccbcc2701d24679dc26b89c6af286a5756d6162072032167090e6723cd869030b287d8250ccf6720636d05f595e0c01332212ebd46716bfef2a54de917bb2b
    chat_room_key_base: 121f116620c4bd069032f96a434cf5f9
    chat_session_key_base: 425e84d42d14d8513d1094dbff6f2b71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  key_pass:
    chat_room_key_base: <%=ENV['CHAT_ROOM_KEY_BASE']%>
    chat_session_key_base: <%ENV['CHAT_SESSION_KEY_BASE']%>
